version: 2.1
jobs:
  app-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - 1d:36:20:c9:5b:c7:c7:f9:20:86:84:7b:57:50:c4:f5
      - run:
          name: "Building Hello World"
          command: |
            echo "This is application repo"
            git config user.email "demo@gmail.com"
            git config user.name "CircleCI Job"
            ls -la
            sed 's/__NGINXTAG__/applatest/g' helm/values.${APP_ENV}.yaml
            git add -A
            git commit --allow-empty -am "Automatic commit from APP build step of CircleCI [skip ci]"
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git push

  helm-change:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - 1d:36:20:c9:5b:c7:c7:f9:20:86:84:7b:57:50:c4:f5
      - run:
          name: "Hello Repo"
          command: |
            echo "This is Helm repo"
            git config user.email "demo@gmail.com"
            git config user.name "CircleCI Job"
            ls -la
            echo ${APP_ENV}
            sed -i 's/__NGINXTAG__/helmlatest/g' helm/values.${APP_ENV}.yaml
            git add -A
            git commit --allow-empty -am "Automatic commit from Helm change build step of CircleCI [skip ci]"
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git push

workflows:
  generate-config:
    jobs:
      - app-build
      - helm-change
      